databases:
  - name: donation
    databaseName: donations
    user: sharon

services:
  - type: web
    name: donation
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: donations
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false